services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '4000:4000'
      - '4001:4001'
      - '4002:4002'
      - '4003:4003'
    environment:
      - MONGO_NODES=4000,4001,4002,4003
      - MONGO_HOST=localhost